name: 'metricpulse'
services:
    postgres:
        container_name: '${CONTAINER_NAME_DB:-metricpulse-postgres}'
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
            POSTGRES_DB: ${POSTGRES_DB:-metricpulse_db}
            LC_ALL: ${LC_ALL:-C.UTF-8}
        ports:
            - '${DB_PORT:-5455}:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - localnetwork

volumes:
    postgres-data:

networks:
    localnetwork:
        driver: bridge