// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/server/storage/storage.go
//
// Generated by this command:
//
//	mockgen -source=./internal/server/storage/storage.go -destination=./internal/server/storage/mock_storage.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	entities "github.com/sodiqit/metricpulse.git/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockStorage) GetAllMetrics() (entities.TotalMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].(entities.TotalMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockStorageMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockStorage)(nil).GetAllMetrics))
}

// GetCounterMetric mocks base method.
func (m *MockStorage) GetCounterMetric(metricType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterMetric", metricType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounterMetric indicates an expected call of GetCounterMetric.
func (mr *MockStorageMockRecorder) GetCounterMetric(metricType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterMetric", reflect.TypeOf((*MockStorage)(nil).GetCounterMetric), metricType)
}

// GetGaugeMetric mocks base method.
func (m *MockStorage) GetGaugeMetric(metricType string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGaugeMetric", metricType)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGaugeMetric indicates an expected call of GetGaugeMetric.
func (mr *MockStorageMockRecorder) GetGaugeMetric(metricType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGaugeMetric", reflect.TypeOf((*MockStorage)(nil).GetGaugeMetric), metricType)
}

// InitMetrics mocks base method.
func (m *MockStorage) InitMetrics(metrics entities.TotalMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitMetrics", metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitMetrics indicates an expected call of InitMetrics.
func (mr *MockStorageMockRecorder) InitMetrics(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitMetrics", reflect.TypeOf((*MockStorage)(nil).InitMetrics), metrics)
}

// SaveCounterMetric mocks base method.
func (m *MockStorage) SaveCounterMetric(metricType string, value int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCounterMetric", metricType, value)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCounterMetric indicates an expected call of SaveCounterMetric.
func (mr *MockStorageMockRecorder) SaveCounterMetric(metricType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCounterMetric", reflect.TypeOf((*MockStorage)(nil).SaveCounterMetric), metricType, value)
}

// SaveGaugeMetric mocks base method.
func (m *MockStorage) SaveGaugeMetric(metricType string, value float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGaugeMetric", metricType, value)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveGaugeMetric indicates an expected call of SaveGaugeMetric.
func (mr *MockStorageMockRecorder) SaveGaugeMetric(metricType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGaugeMetric", reflect.TypeOf((*MockStorage)(nil).SaveGaugeMetric), metricType, value)
}
